[package]
name = "dragnit"
version = "0.1.0"
authors = ["rostegg"]
edition = "2018"
repository = "https://github.com/crimthy/dragnit"
license = "MIT"
description = "Schema-based serializing library  (part of magister project)"
