[package]
name = "dragnit"
version = "0.1.0"
authors = ["rostegg"]
edition = "2018"
repository = "https://github.com/crimthy/dragnit"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
